[WAM]
Title=WAM Coin
Address=
Ip=127.0.0.1
Port=9554
Username=
Password=
AddressPrefix=73
ScriptPrefix=135
SecretPrefix=190
COIN=100000000
MinimumAmount=0
TxVersion=2
DustAmount=0
CreateTxMethod=BTC
GetNewKeySupported=false
ImportWithNoScanSupported=false
MinTxFee=10000
BlockTime=120
FeePerByte=10
Confirmations=60
