#!/bin/bash
# ===========================================================================
#  audit_repo.sh -- does the repository still say what is true?
# ===========================================================================
#
#      bash scripts/audit_repo.sh
#
#  A project's documentation rots silently. A consensus rule changes and eleven
#  files still describe the old one; an asset is renamed and a page links to
#  nothing; a chain is re-launched and a listing page names a genesis block that
#  no longer exists. None of it breaks a build. All of it is read by exactly the
#  people whose opinion matters most -- reviewers, integrators, exchanges -- and
#  to them a stale number is indistinguishable from a lie.
#
#  This script is the check that a person cannot be relied on to repeat. It
#  fails loudly and it is cheap enough to run before every push.
#
#  What it refuses to let pass:
#
#    1. A file path referenced anywhere that does not exist
#    2. Any superseded genesis hash, anywhere
#    3. Any superseded vesting fact (the claim itself: check_published_claims.py)
#    4. The three copies of the vesting schedule disagreeing
#    5. References to directories that were retired
#    6. Placeholder values that were meant to be replaced before launch
# ===========================================================================

set -uo pipefail

# An interpreter that is actually Python: `python3` on Windows is a
# Microsoft Store stub that runs nothing and exits 49.
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
. "$SCRIPTS_DIR/lib/python.sh"
. "$SCRIPTS_DIR/lib/quoted.sh"

# Files carrying $1, ignoring lines the author marked as quotation.
#
# grep finds the candidates; the marks decide. Two lines of this script used
# to end `grep -vE "$EXCLUDE|audit_repo"` -- excluding this file by name,
# because an auditor searching for forbidden strings necessarily contains
# them. That worked for exactly one file and blinded the audit to it: a
# genuinely stale hash pasted into this script would never have been seen.
# Worse, any other file that documented what the audit forbids failed it for
# saying so.
# It also asks git what is in the repository, rather than asking the disk.
#
# Check 1 above learned this on 2026-08-31: "asking the filesystem instead of
# git is how this check passed on the machine that happens to hold the ignored
# file and failed on every clean checkout". Check 2 never learned it, and on
# 6 September it reported two superseded genesis hashes in ops/state.json --
# an untracked, gitignored runtime file that had captured the error output of
# a broken intermediate run of this very script. A finding about nothing, in a
# file no clone contains, which is the same fault in the other direction.
#
# An audit of the repository reads what the repository has.
files_matching() {
    local pat="$1"; shift
    local f out=""
    while IFS= read -r f; do
        [ -n "$f" ] || continue
        git check-ignore -q "$f" 2>/dev/null && continue
        git ls-files --error-unmatch "$f" >/dev/null 2>&1 || continue
        if unquoted "$f" 2>/dev/null | grep -qiE "$pat"; then
            out="$out$f
"
        fi
    done <<EOF
$(grep -rliE "$pat" "$@" 2>/dev/null | grep -vE "$EXCLUDE" || true)
EOF
    printf '%s' "$out"
}

cd "$(dirname "${BASH_SOURCE[0]}")/.."

RED=$'\033[31m'; GRN=$'\033[32m'; YLW=$'\033[33m'; CYN=$'\033[36m'; OFF=$'\033[0m'
FAILURES=0
fail() { printf '  %sFAIL%s  %s\n' "$RED" "$OFF" "$*"; FAILURES=$((FAILURES + 1)); }
ok()   { printf '  %sok%s    %s\n' "$GRN" "$OFF" "$*"; }
step() { printf '\n%s%s%s\n' "$CYN" "$*" "$OFF"; }

# Everything below skips build output, dependencies and untracked scratch.
SEARCH=(--include=*.md --include=*.html --include=*.js --include=*.py
        --include=*.sh --include=*.cpp --include=*.h --include=*.json
        --include=*.service --include=*.yml)
# site/*/index.html is generated by scripts/build_pages.py from documents this
# audit already reads. Auditing the copy adds no coverage and does add false
# alarms, because the copy has markup in it and several checks here are
# proximity-based. The first one fired the day the pages were generated: the
# whitepaper sentence
#
#     Of that, **none** is liquid on launch day  # wam:quote-line
#
# is negated correctly in markdown -- `none.{0,4} is liquid` spans the two
# asterisks -- and in HTML the same words are separated by `</strong> `, which
# is nine characters. The negation missed, and the audit reported that we were
# claiming the reserve is liquid at launch, in the very sentence denying it.  # wam:quote-line
#
# Excluding generated output is the fix rather than widening the pattern:
# a copy cannot disagree with its source, so there is nothing there to audit.
EXCLUDE='node_modules|^\./build/|^\./out/|^\./brand/legacy/|^\./PROGRESS\.md|^\./review/'
EXCLUDE="$EXCLUDE"'|^\./site/[a-z-]+/index\.html'

# ---------------------------------------------------------------------------
step "1. every referenced file exists"

# Files that are referenced on purpose without existing in the repository:
# configs a user creates from an example, and anything .gitignore keeps out.
#
# pool/config-mainnet.json is the pool's mainnet configuration, written on
# the pool host on 2026-08-30 and named in docs/LAUNCH_DAY.md. It carries
# the mainnet RPC password and therefore cannot live here. Named explicitly
# rather than caught by the .*config.json rule, so that its absence stays a
# decision somebody made rather than a pattern that happened to cover it.
EXPECTED_ABSENT='pool/config\.json|pool/config-mainnet\.json|bots/config\.json|.*/config\.json$'

# -o without -h prints "path:match", so the exclusion can filter on the file
# the reference lives in. With -h the filenames are gone and $EXCLUDE matches
# nothing -- which is why this first reported every path inside legacy/, a
# directory it is explicitly told to skip.
# Read through `unquoted`, like every other text check in this file.
#
# This section was the one that did not, and on 12 September it went red about
# a comment whose whole purpose was to record two filenames that had been
# WRONG -- scripts/test/test_alert_text.py had named two senders that do not
# exist, this check caught it within the hour, and then the sentence explaining
# the mistake re-created it. A reference to a missing file and a sentence
# quoting the name of one are the same bytes; the wam:quote marks are how an
# author says which is which, and the rest of this script has honoured them
# since it was written.
#
# The loop reads tracked files one at a time instead of letting grep walk the
# tree, because `unquoted` works on a file. It is slower and it is a few
# hundred files. `git ls-files` also drops everything .gitignore covers, which
# the old form had to ask git about separately, one path at a time.
MISSING=0
REFS="$(for f in $(git ls-files 2>/dev/null); do
            case "$f" in
                *.md|*.html|*.js|*.py|*.sh|*.cpp|*.h|*.json|*.service|*.yml) ;;
                *) continue ;;
            esac
            # "./$f", not "$f". EXCLUDE is anchored on ^\./ because it was
            # written for `grep -r .`, and git ls-files prints bare paths --
            # so testing the bare path makes every anchored exclusion stop
            # matching, silently, and the check starts reporting the
            # generated site pages and brand/legacy that it is explicitly
            # told to skip. One prefix keeps a single definition of EXCLUDE
            # instead of a second copy that has to be kept in step.
            printf './%s\n' "$f" | grep -qE "$EXCLUDE" && continue
            unquoted "$f" 2>/dev/null \
              | grep -oE '(brand|docs|scripts|genesis|deploy|site|pool|explorer|bots|miner)/[A-Za-z0-9/_.-]+\.(svg|png|jpg|md|sh|py|js|json|service|yml)'
        done | sort -u)"
for ref in $REFS; do
    printf '%s' "$ref" | grep -qE "$EXPECTED_ABSENT" && continue
    # Anything .gitignore keeps out is absent on purpose, and asking the
    # filesystem instead of git is how this check passed on the machine that
    # happens to hold the ignored file and failed on every clean checkout --
    # a "works on my machine" fault inside the tool whose job is to catch
    # them. docs/LEGAL_REVIEW_BRIEF_AR.md found it on 2026-08-31.
    git check-ignore -q "$ref" 2>/dev/null && continue
    [ -e "$ref" ] || { fail "referenced but missing: $ref"; MISSING=$((MISSING + 1)); }
done
[ "$MISSING" = 0 ] && ok "no broken file references"

# ---------------------------------------------------------------------------
step "2. no superseded genesis hash survives"

# Every hash this project has ever asserted and then replaced.
#
# Marked as quotation, because naming them is how they are forbidden. This
# used to be handled by excluding this whole file from the search by name,
# which also meant a genuinely stale hash pasted anywhere else in this script
# would never have been found. Now only the list is exempt, and the rest of
# the file is searched like every other.
# wam:quote-begin
DEAD_HASHES=(
    b66685143044db0a   # testnet, before the reserve was locked
    2b1469b34052506a   # its merkle root
    1fa171c2abc3cd0b   # regtest, same
    bbbd737e2aa2fd83   # mainnet, burn-address placeholder
    51e7dd7b7b6e4684   # its merkle root
    52a818ac926d30d8   # mainnet merkle, first tranche unlocked
)
# wam:quote-end
DEAD=0
for h in "${DEAD_HASHES[@]}"; do
    HITS=$(files_matching "$h" "${SEARCH[@]}" .)
    [ -n "$HITS" ] && { fail "superseded hash $h still in: $(echo $HITS | tr '\n' ' ')"; DEAD=$((DEAD + 1)); }
done
[ "$DEAD" = 0 ] && ok "no superseded genesis hash anywhere"

# ---------------------------------------------------------------------------
step "3. no superseded vesting fact survives"

# Stale FACTS only -- strings that were true before 2026-08-18 and can never
# be true again. Not topics.
#
# `liquid at launch` and `liquid on launch day` used to be in this list, and  # wam:quote-line
# they are topics: fifteen lines in nine files say those words in order to
# deny them. Sixteen hand-written phrases in a NEGATED list tried to tell a
# claim from its denial, and that list could hide a real violation, which is
# the worst thing a check can do. A line reading
#
# wam:quote-begin
#     the reserve is liquid at launch, but you must not spend it  # wam:quote-line
# wam:quote-end
#
# was rescued by `must not` and passed in silence.
#
# The claim itself is checked properly by check_published_claims.py, which
# does not match topics at all: it reads the unlock timestamps out of
# wam-params.h and fails any document stating a date consensus does not
# enforce, plus the claim FORMS ("first tranche ... liquid ... launch"). That
# compares against what the network does, which is the only thing worth
# comparing against. CONTRIBUTING.md was added to its list on 6 September,
# the one published file it did not read.
#
# What is left here is the six that need no judgement, and the handful of
# places that quote them are marked with wam:quote-line.
# wam:quote-begin
STALE_FACTS='1\.82%|20% liquid|unlocked at genesis|tranche 1 is spendable'
STALE_FACTS="$STALE_FACTS|launch working capital|vested to 2030"
STALE_FACTS="$STALE_FACTS|liquid at launch|liquid on launch day"
# wam:quote-end

STALE=""
for f in $(files_matching "$STALE_FACTS" "${SEARCH[@]}" .); do
    STALE="$STALE$(unquoted "$f" | grep -niE "$STALE_FACTS" | sed "s|^|$f:|")
"
done
STALE="$(printf '%s' "$STALE" | grep -v '^$' || true)"
if [ -n "$STALE" ]; then
    fail "text still states a fact the vesting schedule replaced:"
    printf '%s\n' "$STALE" | head -8 | sed 's/^/          /'
else
    ok "no superseded vesting fact survives (the claim itself: check_published_claims.py)"
fi

# ---------------------------------------------------------------------------
step "4. the three vesting tables agree"

if "$PY" scripts/check_vesting_sync.py >/dev/null 2>&1; then
    ok "wam-params.h, the generator and the explorer carry the same schedule"
else
    fail "vesting schedules disagree -- run scripts/check_vesting_sync.py"
fi

# ---------------------------------------------------------------------------
step "5. retired components are not referenced"

RETIRED=0
for dir in telegram; do
    HITS=$(files_matching "$dir/" "${SEARCH[@]}" .)
    [ -n "$HITS" ] && { fail "retired '$dir/' referenced in: $(echo $HITS | tr '\n' ' ')"; RETIRED=$((RETIRED + 1)); }
done
[ "$RETIRED" = 0 ] && ok "no references to retired directories"

# ---------------------------------------------------------------------------
step "6. placeholders that must not reach launch"

PLACEHOLDER=0
BURN="WNg2svm2qApxheBKndKGQ9sRwporvRgRpT"

# The burn address, hash160 of twenty zero bytes. Anything paid to it is gone.
if grep -q "WAM_FOUNDER_ADDRESS_MAINNET = \"$BURN\"" src/wam/chainparams.cpp 2>/dev/null; then
    fail "the mainnet founder address is still the burn placeholder"
    PLACEHOLDER=$((PLACEHOLDER + 1))
fi
if grep -q "WAM_TREASURY_ADDRESS_MAINNET = \"$BURN\"" src/wam/chainparams.cpp 2>/dev/null; then
    printf '  %swarn%s  the mainnet treasury address is still the burn placeholder.\n' "$YLW" "$OFF"
    printf '        750,000 WAM of operating income would be destroyed. Generate a\n'
    printf '        second key offline -- not the founder key -- before launch.\n'
fi
if grep -rq "WCHANGEme" pool/config.json 2>/dev/null; then
    fail "pool/config.json still has a placeholder payout address"
    PLACEHOLDER=$((PLACEHOLDER + 1))
fi

# The whole point of two constants is that they hold two different values.
# Setting them back to one address would restore the arrangement that made
# treasury spending indistinguishable from founder selling, and it would do it
# silently -- nothing fails, the chain runs, and only an auditor notices.
# sed, not `grep -oP ... \K`. On 5 September 2026 grep here answered
#
#     grep: -P supports only unibyte and UTF-8 locales
#
# and printed nothing, so F and T were both empty -- and `[ -n "$F" ]` is
# false for an empty string, so this check reported that the founder and
# treasury addresses differ without ever having read either of them.
#
# A false alarm is annoying. This was the other kind: a security check that
# silently passes. The two constants exist so that treasury spending cannot be
# mistaken for founder selling, and the audit was green about a comparison it
# had not made. Both extractions are now portable, and an empty result is
# treated as a failure of the check rather than as agreement.
for NET in MAINNET TESTNET; do
    F=$(sed -n "s/.*WAM_FOUNDER_ADDRESS_$NET *= *\"\([^\"]*\)\".*/\1/p" src/wam/chainparams.cpp 2>/dev/null | head -1)
    T=$(sed -n "s/.*WAM_TREASURY_ADDRESS_$NET *= *\"\([^\"]*\)\".*/\1/p" src/wam/chainparams.cpp 2>/dev/null | head -1)
    if [ -z "$F" ] || [ -z "$T" ]; then
        fail "$NET founder/treasury addresses could not be read from chainparams.cpp"
        PLACEHOLDER=$((PLACEHOLDER + 1))
    elif [ "$F" = "$T" ]; then
        fail "$NET founder and treasury are the same address; they must differ"
        PLACEHOLDER=$((PLACEHOLDER + 1))
    fi
done

[ "$PLACEHOLDER" = 0 ] && ok "no launch-blocking placeholders; founder and treasury differ"

# ---------------------------------------------------------------------------
step "7. claims about maturity and duration are current"

# The founder reserve was locked over five years, not four, on 2026-08-18. The
# whole documentation set said four, in seven places, and none of the earlier
# checks noticed -- they searched for "liquid at launch" and this is a duration.  # wam:quote-line
# A reader comparing "vested over 4 years" against a schedule ending in 2031
# concludes the project cannot keep its own numbers straight.
DURATION=$(grep -rniE '(vested|locked|vesting).{0,24}(4 years|four years)|20% per year to 2030|to 2030-09-15' \
           "${SEARCH[@]}" . 2>/dev/null | grep -vE "$EXCLUDE|audit_repo" \
           | grep -viE 'zcash|dash|decred|monero|for comparison' || true)
if [ -n "$DURATION" ]; then
    fail "the reserve is described as four years somewhere; it is five:"
    printf '%s\n' "$DURATION" | head -6 | sed 's/^/          /'
else
    ok "the reserve is described as five years everywhere"
fi

# Claims that were true before the code was first compiled. They are the first
# thing a reviewer reads about maturity, and they age badly and silently.
MATURITY=$(grep -rniE 'nothing has been compiled|never been through a compiler|have never been applied|no chain exists yet' \
           "${SEARCH[@]}" . 2>/dev/null | grep -vE "$EXCLUDE|audit_repo" || true)
if [ -n "$MATURITY" ]; then
    fail "text still says the project has never been compiled:"
    printf '%s\n' "$MATURITY" | head -4 | sed 's/^/          /'
else
    ok "no stale claim that nothing has been built"
fi

# ---------------------------------------------------------------------------
step "8. the integration files still match the chain"

# integration/ duplicates chain parameters for venues that consume a config
# file rather than a form. They cannot share a definition -- one is JSON that
# Komodo reads, one is an ini that Block DX reads, and the source of truth is
# C++. So they are copies, and a copy that drifts is an integration that fails
# on the first connection, from a venue that does not come back to ask why.
INTEG=0
if [ -d integration ]; then
    # -oE twice rather than -oP with \K. grep refused -P on the founder's
    # machine -- "supports only unibyte and UTF-8 locales" -- and printed
    # nothing, so GEN_ALL was empty, so every hash in every published document
    # failed the comparison below. The audit accused the real mainnet and
    # testnet genesis hashes of being wrong, using a tool that had already said
    # it could not answer.
    GEN_MAIN=$(grep -oE 'hashGenesisBlock == uint256S\("0x[0-9a-f]{64}' src/wam/chainparams.cpp | grep -oE '[0-9a-f]{64}' | head -1)
    GEN_TEST=$(grep -oE 'hashGenesisBlock == uint256S\("0x[0-9a-f]{64}' src/wam/chainparams.cpp | grep -oE '[0-9a-f]{64}' | sed -n 2p)

    # Every 64-hex string in the files venues read must be a chain hash this
    # source declares -- or must say on the same line what else it is.
    #
    # This used to name integration/basicswap/wam.json and check two hashes in
    # it. When BasicSwap turned out to consume a Python package rather than
    # JSON and the file went away, the check reported "wrong mainnet genesis
    # hash" about a file that did not exist: a true failure with a false
    # reason, which sends the next reader looking in the wrong place.
    #
    # Asking the question of every file instead means no filename here can go
    # stale, and a genesis hash that survives a re-mine anywhere in the
    # published material is caught wherever it is hiding.
    GEN_ALL="$(grep -oE 'hashGenesisBlock == uint256S\("0x[0-9a-f]{64}' src/wam/chainparams.cpp | grep -oE '[0-9a-f]{64}')"
    while IFS= read -r line; do
        [ -n "$line" ] || continue
        f="${line%%:*}"; rest="${line#*:}"
        h="$(printf '%s' "$rest" | grep -oE '\b[0-9a-f]{64}\b' | head -1)"
        printf '%s\n' "$GEN_ALL" | grep -qx "$h" && continue
        # Not a genesis hash. It may still be legitimate -- the listing package
        # quotes the genesis merkle root -- but it has to say so where it sits,
        # so a stale hash can never pass as a labelled one.
        # 'merkle' was the only label this accepted, because the genesis
        # merkle root was the only legitimate non-genesis hash in published
        # material. The treasury ledger added a second kind on 2026-09-22:
        # a transaction id, which has to be publishable or the promise to
        # publish every treasury spend cannot be kept.
        #
        # The discipline is unchanged and is the whole point -- the word has
        # to sit on the SAME LINE as the hash, so a hash that loses its
        # meaning, or a stale one pasted in later, still fails.
        printf '%s' "$rest" | grep -qiE 'merkle|txid|transaction id' && continue
        fail "$f carries ${h:0:16}..., which is neither a genesis hash nor labelled"
        INTEG=$((INTEG+1))
    # Tracked files only, not the working tree. integration/komodo/ can hold
    # a built submission directory containing KomodoPlatform's own 782-entry
    # coins file, and scanning that reports every other project's constants
    # as ours being wrong -- which is a check crying wolf about a file that
    # is not ours and is not committed. Anything gitignored is by definition
    # not something this repository claims.
    done <<< "$(git ls-files -z integration/ docs/ 2>/dev/null | xargs -0 grep -EnH '\b[0-9a-f]{64}\b' 2>/dev/null)"

    # Address prefixes, in every file that repeats them. A named file that has
    # gone missing is reported as missing rather than as wrong.
    #
    # The Block DX conf is a glob rather than a name because it is called
    # after its ver_id, which carries the release it targets and therefore
    # changes whenever we retarget. It went from wamcoin--v0.1.3.conf to
    # wam--v0.1.6.conf on 2026-08-29 and this list then reported that a
    # venue's files had been lost. A glob cannot go stale, and if there is
    # ever more than one conf, checking all of them is the more correct
    # thing to do anyway.
    for f in integration/komodo/coin-entry.json \
             integration/blockdx/xbridge-confs/*.conf \
             integration/basicswap/chainparams.py; do
        if [ ! -f "$f" ]; then
            fail "$f is gone -- either it moved and this list is stale, or a venue's files were lost"
            INTEG=$((INTEG+1)); continue
        fi
        grep -q '\b73\b' "$f" && grep -q '\b135\b' "$f" \
            || { fail "$f is missing an address prefix (73 pubkey / 135 script)"; INTEG=$((INTEG+1)); }
    done

    # Every SLIP-44 coin type written in integration/ must be the one the
    # source declares. Not "must be absent" -- the files now carry it, because
    # wamd derives there and a venue's config describes the wallet it will
    # talk to. What must not happen is a second opinion: a number typed into
    # one file and forgotten when the other changes.
    #
    # 1 is exempt. SLIP-44 reserves it for every test chain, so it means
    # "testnet" rather than "WAM" and is correct in the testnet and regtest
    # blocks of the same files.
    WANT_BIP44="$(grep -oE 'WAM_BIP44_COIN_TYPE[[:space:]]*=[[:space:]]*(0x[0-9A-Fa-f]+|[0-9]+)' \
        src/wam/wam-params.h 2>/dev/null | grep -oE '(0x[0-9A-Fa-f]+|[0-9]+)$' | tail -1)"
    if [ -n "$WANT_BIP44" ]; then
        WANT_DEC=$(printf '%d' "$WANT_BIP44" 2>/dev/null)
        while IFS= read -r hit; do
            [ -n "$hit" ] || continue
            n="$(printf '%s' "$hit" | grep -oE '[0-9]+' | tail -1)"
            [ "$n" = "1" ] && continue
            [ "$n" = "$WANT_DEC" ] && continue
            fail "$hit"
            fail "  ...is not $WANT_DEC, which src/wam/wam-params.h declares"
            INTEG=$((INTEG+1))
        done <<< "$(git ls-files -z integration/ 2>/dev/null | xargs -0 grep -EnH \
            "^[^#]*\"?(bip44|derivation_path|coin_type)\"?[[:space:]]*[:=][[:space:]]*[\"']?m?/?4?4?'?/?[0-9]" \
            2>/dev/null)"
    else
        fail "WAM_BIP44_COIN_TYPE is not declared in src/wam/wam-params.h"
        INTEG=$((INTEG+1))
    fi

    # The message prefix Komodo asks for by name, against the patch rule.
    if grep -q 'WAM Coin Signed Message' scripts/patch_upstream.py 2>/dev/null; then
        grep -q 'WAM Coin Signed Message' integration/komodo/coin-entry.json 2>/dev/null \
            || { fail "komodo/coin-entry.json does not carry the WAM message prefix"; INTEG=$((INTEG+1)); }
    fi

    # A derivation_path used to be forbidden outright here, because there was
    # no number to put in it. There is one now -- wamd derives at it -- so the
    # question changed from "is it present" to "does it agree with the source",
    # which the check above asks of every file at once. Two checks answering
    # the same question differently is how one of them ends up wrong.

    [ "$INTEG" = 0 ] && ok "integration/ agrees with the consensus source"
else
    ok "no integration/ directory yet"
fi

# ---------------------------------------------------------------------------
printf '\n%s\n' "$(printf '=%.0s' {1..70})"
if [ "$FAILURES" = 0 ]; then
    printf ' %sthe repository agrees with itself%s\n' "$GRN" "$OFF"
else
    printf ' %s%d check(s) failed%s\n' "$RED" "$FAILURES" "$OFF"
fi
printf '%s\n' "$(printf '=%.0s' {1..70})"
exit $((FAILURES > 0))
